# Generated by Django 3.0.3 on 2020-02-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=252)),
                ('last_name', models.CharField(max_length=252)),
                ('phone_number', models.CharField(max_length=252, unique=True)),
                ('email_address', models.EmailField(max_length=128, unique=True)),
                ('birth_certificate', models.FileField(upload_to='documents/')),
                ('national_id', models.FileField(upload_to='documents/')),
                ('school_name', models.CharField(max_length=252)),
                ('address', models.CharField(max_length=252)),
                ('academic_level', models.CharField(max_length=100)),
                ('year_of_completion', models.CharField(max_length=100)),
                ('reason_to_be_sponsored', models.TextField(max_length=1000)),
                ('recomendation_letter', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='SponsporsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=252)),
                ('last_name', models.CharField(max_length=252)),
                ('email_address', models.EmailField(max_length=252, unique=True)),
                ('occupation', models.CharField(max_length=100)),
                ('sponsored_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorshipapp.ApplicantInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.CharField(max_length=100)),
                ('applicant_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorshipapp.ApplicantInfo')),
            ],
        ),
    ]
